.TH "src könyvtárreferencia" 3 "Version 1.0.0" "sikidom" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src könyvtárreferencia
.SH SYNOPSIS
.br
.PP
.SS "Fájlok"

.in +1c
.ti -1c
.RI "fájl \fBpont\&.cpp\fP"
.br
.ti -1c
.RI "fájl \fBpont\&.h\fP"
.br
.ti -1c
.RI "fájl \fBsikidom\&.cpp\fP"
.br
.ti -1c
.RI "fájl \fBsikidom\&.h\fP"
.br
.ti -1c
.RI "fájl \fBtomb\&.hpp\fP"
.br
.in -1c
