.TH "gtest_lite" 3 "Version 1.0.0" "sikidom" \" -*- nroff -*-
.ad l
.nh
.SH NAME
gtest_lite \- \fBgtest_lite\fP: a keretrendszer függvényinek és objektumainak névtere  

.SH SYNOPSIS
.br
.PP
.SS "Osztályok"

.in +1c
.ti -1c
.RI "struct \fBTest\fP"
.br
.in -1c
.SS "Függvények"

.in +1c
.ti -1c
.RI "template<typename T1 , typename T2 > std::ostream & \fBEXPECT_\fP (T1 exp, T2 act, bool(*pred)(T1, T2), const char *file, int line, const char *expr, const char *lhs='elvart', const char *rhs='aktual')"
.br
.RI "általános sablon a várt értékhez\&. "
.ti -1c
.RI "template<typename T1 , typename T2 > std::ostream & \fBEXPECT_\fP (T1 *exp, T2 *act, bool(*pred)(T1 *, T2 *), const char *file, int line, const char *expr, const char *lhs='elvart', const char *rhs='aktual')"
.br
.RI "pointerre specializált sablon a várt értékhez\&. "
.ti -1c
.RI "std::ostream & \fBEXPECTSTR\fP (const char *exp, const char *act, bool(*pred)(const char *, const char *), const char *file, int line, const char *expr, const char *lhs='elvart', const char *rhs='aktual')"
.br
.ti -1c
.RI "template<typename T1 , typename T2 > bool \fBeq\fP (T1 a, T2 b)"
.br
.ti -1c
.RI "bool \fBeqstr\fP (const char *a, const char *b)"
.br
.ti -1c
.RI "template<typename T1 , typename T2 > bool \fBne\fP (T1 a, T2 b)"
.br
.ti -1c
.RI "bool \fBnestr\fP (const char *a, const char *b)"
.br
.ti -1c
.RI "template<typename T1 , typename T2 > bool \fBle\fP (T1 a, T2 b)"
.br
.ti -1c
.RI "template<typename T1 , typename T2 > bool \fBlt\fP (T1 a, T2 b)"
.br
.ti -1c
.RI "template<typename T1 , typename T2 > bool \fBge\fP (T1 a, T2 b)"
.br
.ti -1c
.RI "template<typename T1 , typename T2 > bool \fBgt\fP (T1 a, T2 b)"
.br
.ti -1c
.RI "template<typename T > bool \fBalmostEQ\fP (T a, T b)"
.br
.in -1c
.SS "Változók"

.in +1c
.ti -1c
.RI "static \fBTest\fP & \fBtest\fP = \fBTest::getTest\fP()"
.br
.in -1c
.SH "Részletes leírás"
.PP 
\fBgtest_lite\fP: a keretrendszer függvényinek és objektumainak névtere 
.SH "Függvények dokumentációja"
.PP 
.SS "template<typename T > bool gtest_lite::almostEQ (T a, T b)"
Segédsablon valós számok összehasonlításához Nem bombabiztos, de nekünk most jó lesz Elméleti hátér: http://www.cygnus-software.com/papers/comparingfloats/comparingfloats.htm 
.SS "template<typename T1 , typename T2 > bool gtest_lite::eq (T1 a, T2 b)"
segéd sablonok a relációkhoz\&. azért nem STL (algorithm), mert csak a függvény lehet, hogy menjen a deduckció 
.SS "bool gtest_lite::eqstr (const char * a, const char * b)\fR [inline]\fP"

.SS "template<typename T1 , typename T2 > std::ostream & gtest_lite::EXPECT_ (T1 * exp, T2 * act, bool(*)(T1 *, T2 *) pred, const char * file, int line, const char * expr, const char * lhs = \fR'elvart'\fP, const char * rhs = \fR'aktual'\fP)"

.PP
pointerre specializált sablon a várt értékhez\&. 
.SS "template<typename T1 , typename T2 > std::ostream & gtest_lite::EXPECT_ (T1 exp, T2 act, bool(*)(T1, T2) pred, const char * file, int line, const char * expr, const char * lhs = \fR'elvart'\fP, const char * rhs = \fR'aktual'\fP)"

.PP
általános sablon a várt értékhez\&. 
.SS "std::ostream & gtest_lite::EXPECTSTR (const char * exp, const char * act, bool(*)(const char *, const char *) pred, const char * file, int line, const char * expr, const char * lhs = \fR'elvart'\fP, const char * rhs = \fR'aktual'\fP)\fR [inline]\fP"
stringek összehasonlításához\&. azért nem spec\&. mert a sima EQ-ra másként kell működnie\&. 
.SS "template<typename T1 , typename T2 > bool gtest_lite::ge (T1 a, T2 b)"

.SS "template<typename T1 , typename T2 > bool gtest_lite::gt (T1 a, T2 b)"

.SS "template<typename T1 , typename T2 > bool gtest_lite::le (T1 a, T2 b)"

.SS "template<typename T1 , typename T2 > bool gtest_lite::lt (T1 a, T2 b)"

.SS "template<typename T1 , typename T2 > bool gtest_lite::ne (T1 a, T2 b)"

.SS "bool gtest_lite::nestr (const char * a, const char * b)\fR [inline]\fP"

.SH "Változók dokumentációja"
.PP 
.SS "\fBTest\fP& gtest_lite::test = \fBTest::getTest\fP()\fR [static]\fP"
A statikus referencia minden fordítási egységben keletkezik, de mindegyik egyetlen példányra fog hivatkozni a singleton minta miatt 
.SH "Szerző"
.PP 
Ezt a dokumentációt a Doxygen készítette a sikidom projekthez a forráskódból\&.
