.TH "C:/Users/matyas/code/sikidom/src/main.cpp" 3 "Version 1.0.0" "sikidom" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/matyas/code/sikidom/src/main.cpp
.SH SYNOPSIS
.br
.PP
\fR#include <iostream>\fP
.br
\fR#include <fstream>\fP
.br
\fR#include <sstream>\fP
.br
\fR#include <stdexcept>\fP
.br
\fR#include 'gtest_lite\&.h'\fP
.br
\fR#include 'pont\&.h'\fP
.br
\fR#include 'sikidom\&.h'\fP
.br
\fR#include 'tomb\&.hpp'\fP
.br

.SS "Függvények"

.in +1c
.ti -1c
.RI "int \fBmain\fP (int argc, char **argv)"
.br
.in -1c
.SH "Függvények dokumentációja"
.PP 
.SS "int main (int argc, char ** argv)"

.SH "Szerző"
.PP 
Ezt a dokumentációt a Doxygen készítette a sikidom projekthez a forráskódból\&.
