.TH "src/pont.h" 3 "Version 1.0.0" "sikidom" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/pont.h
.SH SYNOPSIS
.br
.PP
\fR#include <iostream>\fP
.br

.SS "Osztályok"

.in +1c
.ti -1c
.RI "class \fBPont\fP"
.br
.RI "\fBPont\fP osztály A pontokat a síkon tárolja, x és y koordinátákkal\&. "
.in -1c
.SS "Függvények"

.in +1c
.ti -1c
.RI "double \fBdst\fP (const \fBPont\fP &a, const \fBPont\fP &b)"
.br
.RI "két pont közötti távolság számító függvény\&. "
.in -1c
.SH "Függvények dokumentációja"
.PP 
.SS "double dst (const \fBPont\fP & a, const \fBPont\fP & b)"

.PP
két pont közötti távolság számító függvény\&. 
.PP
\fBParaméterek\fP
.RS 4
\fIa\fP egyik pont 
.br
\fIb\fP másik pont 
.RE
.PP
\fBVisszatérési érték\fP
.RS 4
a két pont távolsága 
.RE
.PP

.SH "Szerző"
.PP 
Ezt a dokumentációt a Doxygen készítette a sikidom projekthez a forráskódból\&.
