.TH "src/sikidom.cpp" 3 "Version 1.0.0" "sikidom" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/sikidom.cpp
.SH SYNOPSIS
.br
.PP
\fR#include <cmath>\fP
.br
\fR#include <istream>\fP
.br
\fR#include <algorithm>\fP
.br
\fR#include 'pont\&.h'\fP
.br
\fR#include 'sikidom\&.h'\fP
.br

.SS "Függvények"

.in +1c
.ti -1c
.RI "std::istream & \fBoperator>>\fP (std::istream &is, \fBSikidom\fP **sikidom)"
.br
.RI "\fBSikidom\fP osztály beolvasó operátora\&. A függvény beolvassa a síkidomot a megadott input streamből\&. "
.ti -1c
.RI "std::ostream & \fBoperator<<\fP (std::ostream &os, const \fBSikidom\fP *const sikidom)"
.br
.RI "\fBSikidom\fP osztály kiíró operátora\&. A függvény kiírja a síkidomot a megadott output streambe\&. "
.ti -1c
.RI "bool \fBIsOnTriangle\fP (const \fBPont\fP &P, const \fBPont\fP &A, const \fBPont\fP &B, const \fBPont\fP &C)"
.br
.RI "IsOnTriangle függvény\&. A függvény eldönti, hogy egy pont rajta van-e egy háromszögön\&. "
.in -1c
.SH "Függvények dokumentációja"
.PP 
.SS "bool IsOnTriangle (const \fBPont\fP & P, const \fBPont\fP & A, const \fBPont\fP & B, const \fBPont\fP & C)"

.PP
IsOnTriangle függvény\&. A függvény eldönti, hogy egy pont rajta van-e egy háromszögön\&. 
.PP
\fBParaméterek\fP
.RS 4
\fIP\fP a vizsgált pont\&. 
.br
\fIA\fP háromszög egyik csúcsa\&. 
.br
\fIB\fP háromszög másik csúcsa\&. 
.br
\fIC\fP háromszög harmadik csúcsa\&. 
.RE
.PP
\fBVisszatérési érték\fP
.RS 4
true, ha a pont rajta van a háromszögön, egyébként false\&.
.RE
.PP
A kiszamitas modja: https://en.wikipedia.org/wiki/Barycentric_coordinate_system#Determining_location_with_respect_to_a_triangle 
.SS "std::ostream & operator<< (std::ostream & os, const \fBSikidom\fP *const sikidom)"

.PP
\fBSikidom\fP osztály kiíró operátora\&. A függvény kiírja a síkidomot a megadott output streambe\&. 
.PP
\fBParaméterek\fP
.RS 4
\fIos\fP a kimeneti stream\&. 
.br
\fIsikidom\fP a kiírandó síkidomra mutató pointer\&. 
.RE
.PP
\fBVisszatérési érték\fP
.RS 4
A kimeneti stream referenciája\&. 
.RE
.PP

.SS "std::istream & operator>> (std::istream & is, \fBSikidom\fP ** sikidom)"

.PP
\fBSikidom\fP osztály beolvasó operátora\&. A függvény beolvassa a síkidomot a megadott input streamből\&. 
.PP
\fBParaméterek\fP
.RS 4
\fIis\fP a bemeneti stream\&. 
.br
\fIsikidom\fP a beolvasott síkidomra mutató pointer\&. 
.RE
.PP
\fBVisszatérési érték\fP
.RS 4
A bemeneti stream referenciája\&. 
.RE
.PP

.SH "Szerző"
.PP 
Ezt a dokumentációt a Doxygen készítette a sikidom projekthez a forráskódból\&.
