.TH "src/tomb.hpp" 3 "Version 1.0.0" "sikidom" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/tomb.hpp
.SH SYNOPSIS
.br
.PP
\fR#include <stdexcept>\fP
.br

.SS "Osztályok"

.in +1c
.ti -1c
.RI "class \fBTomb< T >\fP"
.br
.RI "Generikus Dinamikus tömb osztály\&. A \fBTomb\fP osztály egy dinamikus tömböt reprezentál, melynek mérete a felhasználó által nem korlátozott\&. "
.ti -1c
.RI "class \fBTomb< T >::iterator\fP"
.br
.RI "iterator osztály\&. Az iterator osztály a \fBTomb\fP osztály iteratora\&. "
.ti -1c
.RI "class \fBTomb< T >::const_iterator\fP"
.br
.RI "\fBconst_iterator\fP osztály\&. Az \fBconst_iterator\fP osztály a \fBTomb\fP osztály const_iteratora\&. "
.in -1c
.SH "Szerző"
.PP 
Ezt a dokumentációt a Doxygen készítette a sikidom projekthez a forráskódból\&.
